### PR TITLE
Add blender mono i18n font for Japanese

### PR DESCRIPTION
**Pull request by shiena**
The font name follows the changes in #463.

### CODE REVIEW

**Comment by luboslenco** [comment]
Yo @shiena, do we need separate fonts for japan, chinese and korean?

**Comment by shiena** [comment]
Yes. Eventually you should separate them.
The designs that are often used for the same letter are different in each country. This is why it is different.
See also this issue.
- https://japanese.stackexchange.com/questions/64590/why-are-japanese-fonts-different-to-chinese
- https://forums.factorio.com/viewtopic.php?t=69040

Also, some characters are not included in font_cjk.ttf and cannot be displayed.

| not include character | unicode | language | english | translated |
|----|----|----|----|----|
|不|U+F967|japanese|Opacity|不透明度|
|履|U+5C65|japanese|History|履歴|
|理|U+7406|chinese|Texture|纹理|

**Comment by shiena** [comment]
I have found a reason why I can't display these three letters.
These characters have a variation selector in Unicode, which defines two code points per character.
And font_cjk.ttf has no font glyphs for some reason, only one code point.
This is due to the font.

For example, the code points for "不" are `U+4E0D` and `U+F967`.
https://www.compart.com/en/unicode/U+4E0D

**Comment by shiena** [comment]
#489 is a better implementation than this, so I'll close it

**Pull request closed without merging**
