### PR TITLE
Warp Node feature

### LINKED ISSUE #576: Warp Node
(https://github.com/armory3d/armorpaint/issues/223)

### PR DESCRIPTION
**Pull request by lidorY**
Implemented the requested feature in #576. 
Resolves #576.
(Suppose to be similar to the same feature in other 3D painting apps, Hopefully right :D..)

The node is partially based on the baking mechanism of the Blur node.
Inputs are:
-  Color: the main texture to warp 
-  Strength (0.0 - 1.0): how much warp to apply
- Angle (degrees 0 - 360): the direction in which we apply the warp 
-  Mask: texture that represents the intensities of the warp for each pixel.

The effect is basically calculating the pixel with which we should replace the current pixel from the Color texture according to the other inputs.

Left side presents the effect applied to a square with a spherical grdient mask (Right side - strength == 0).
warp_example

### CODE REVIEW

**Comment by Hopefullyidontgetbanned** [comment]
wouldn't the mask be an B/W value called "Fac" like mixrgb

**Comment by lidorY** [comment]
> wouldn't the mask be an B/W value called "Fac" like MixRGB, mostly thinking about it for how you want to have consistent terminology since the function would be kinda identical except it would be a slider with 0 representing black and 1 representing white

**Comment by lidorY** [comment]
Updated the interface of the Wrap to be more intuitive and consistent.
- Mask is now converted to 0 - 1 gray scale value, as input from other nodes.
- No "Strength" input (can be achieved by multiplying using a Math node)
- Angle as a value. can get inputs from other nodes (need to be in 0 - 360 value range).
- parse_input_value can parse a compound type as gray scale instead of just it's x value


warp_example2

**Comment by luboslenco** [comment]
Thanks a lot! 👍

**Pull request merged**
