### PR TITLE
Bug fix for FBX Binary 7500

### LINKED ISSUE #363: Error read data mesh fbx import
*ArmorPaint 0.8-b355159, Windows*
Console report fbx export maya 2018 to fbx 
Then import fbx fiele to amorpaint error message console
Error read data mesh fbx import 
Root does not have FBXHeaderExtenxion.FBXVersion(FBXHeaderExtension not found)
Help me! fix it !
THX

### PR DESCRIPTION
**Pull request by PiloeGAO**
Bug fix #363.

Sources:
- https://github.com/assimp/assimp/issues/838
- https://github.com/assimp/assimp/pull/1354

### CODE REVIEW

**Comment by luboslenco** [comment]
Super cool! Wouldn't we be more future proof with `version >= 7500` instead of `version == 7500`? Looks like the same has been asked at https://github.com/assimp/assimp/pull/1354 but then not resolved.

**Comment by PiloeGAO** [comment]
I didn't found any information on the Autodesk website, but we should make this change to prevent new bugs in the future.

**Comment by luboslenco** [comment]
So we should go with `version >= 7500`? Can you include that change? 🙂

**Comment by PiloeGAO** [comment]
I made the change and updated the pull request.

**Comment by luboslenco** [comment]
Thanks again, helps a lot!

**Pull request merged**
